### PR TITLE
correcting typo on variable name and making delivery_mode work

### PR DESCRIPTION
**Pull request by edernucci**
Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/

### CODE REVIEW

**Comment by yaauie** [comment]
@edernucci thank you for finding this and submitting a fix.

Can I get you to sign the [Contributor License Agreement](https://www.elastic.co/contributor-agreement/) so we can accept your fix?

**Comment by edernucci** [comment]
@yaauie Hi there! I already signed it, should I send the signed doc here?

**Comment by yaauie** [comment]
@edernucci It looks like you may have signed with a different e-mail address than the one used on your commit (`****@greenpass.com.br`). Would you mind signing again with that address so our automated CLA-checker is able to find it?

**Comment by yaauie** [comment]
@edernucci since you're continuing to commit to this branch, and I have a separate PR (#9) that includes your originally-proposed fixes, I'm closing this PR.

We do need you to sign the CLA with your `****@greenpass.com.br` e-mail address to merge that PR in order for us to merge it.

**Pull request closed without merging**
