### PR TITLE
correct typo on delivery_mode variable name to make it work correctly

### PR DESCRIPTION
**Pull request by yaauie**
Replaces #8

### CODE REVIEW

**Comment by yaauie** [comment]
CLA check failing for intermediate commit including work by @edernucci from #8. Once they are able to sign the CLA with their `****@greenpass.com.br` e-mail address, this will be ready to merge.

**Comment by elasticcla** [comment]
Hi @yaauie, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/logstash-plugins/logstash-output-jms/pull/9.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by ghost** [comment]
Hi @yaauie, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/logstash-plugins/logstash-output-jms/pull/9.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by edernucci** [comment]
@yaauie @elasticcla I have added the other e-mail address to my profile in order to proceed with verification. Regards!

**Comment by yaauie** [comment]
CLA check please :)

**Pull request merged**
